### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by FantasticFiasco** [antlr/antlrcs#107]
Hi!

Have you considered adopting to [SemVer](https://semver.org/) when publishing packages to nuget.org?

**Comment by sharwell** [comment]
Hi @FantasticFiasco,

Packages published from this repository should no longer be including any breaking changes.

If you have a specific question or concern about the versioning policy, please let me know.

**Comment by FantasticFiasco** [comment]
It's not so much about whether you intend to stay backward compatible as it is that you conform to SemVer. I am writing some code that reads packages from nuget.org, and this package stood out, and because of this it makes it harder to reason about what to expect from different version of your package.

I don't intent to start a flamewar or anything, I'll leave it at this. Thank you for your time and have a great evening.

**Comment by sharwell** [comment]
I do not have any intent to use SemVer, nor do I have any intent to deviate from it.

> I don't intent to start a flamewar or anything

Don't worry, the question was not going to cause a problem. 😄
