### ISSUE TITLE
Version Number mismatch

### ISSUE THREAD

**Issue by Doytoend** [antlr/antlrcs#125]
Hi,

This is more of a clarification on the versioning numbers used.
We have been updating our packages and we wanted to use Antlr3.Runtime version 3.5.2 RC. However when I added the package and looked at the reference properties I found that the Version is set at 3.5.0.2 rather than 3.5.2 is this correct?

From what I gathered 3.5.0.2 is for the Antlr3 package rather than the Antlr3.Runtime package.

![image](https://user-images.githubusercontent.com/15824349/66745377-0b56b580-ee7f-11e9-9050-5c1afcec5e99.png)

**Comment by sharwell** [comment]
@Doytoend There are three version numbers.

* AssemblyVersion: This shows as "Version" in the reference's properties page
* AssemblyFileVersion: This shows as "File version"
* AssemblyInformationalVersion: This shows as "Product version"

The AssemblyVersion affects binding, so to avoid the need for users to add as many assembly binding redirects, the version only changes when the major or minor version changes. In other words, all 3.5.x releases will use the same AssemblyVersion. This policy was established after 3.5.0.2 was released, so the version lock occurred at that point.

**Comment by Doytoend** [comment]
@sharwell Thanks for the clarification. Needed it for documentation.
