### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by petriashev** [antlr/antlrcs#24]
Hello, I created nuget packages in early 2012. Now there is offitial sources on github.
I can give yor ownership on that packages if you give me your nickname on nuget.org.

https://www.nuget.org/packages/Antlr3.StringTemplate/
https://www.nuget.org/packages/Antlr4.StringTemplate/

Can I help you whith this issue?

**Comment by brandondahler** [comment]
I just noticed the NuGet package for StringTemplate v4 is currently at 4.0.6.9004 whereas the current stable release is at 4.0.7.1 , can one of the owners (or @petriashev) update the NuGet package?

**Comment by sharwell** [comment]
The "official" distribution of the StringTemplate 4 package on NuGet is here:

https://www.nuget.org/packages/StringTemplate4

**Comment by sharwell** [comment]
@petriashev I can help you update those packages so they automatically redirect to the package I've released without breaking users. If you can point me to the GitHub repository containing the **.nuspec** file(s), I can send you a pull request to review the changes.

The basic idea is to create a metadata-only package, which doesn't contain any binaries, but instead declares a dependency on the **StringTemplate4** package. When users update to the latest release of the **Antlr4.StringTemplate** package, NuGet will automatically add a new reference to **StringTemplate4** to their project.

**Comment by petriashev** [comment]
Hello, I've added sharwell as owner for my packages. You have to accept this request and change everything you want.

**Comment by brandondahler** [comment]
@sharwell Right now those packages are marked pre-release, can someone deploy one marked stable?

**Comment by sharwell** [comment]
@brandondahler Sure. I marked them as pre-release in order to get feedback on them, but the feedback never came to confirm they worked as expected. :grin:

**Comment by sharwell** [comment]
I published stable releases of ANTLR 3, StringTemplate 3, and StringTemplate 4 to NuGet today.
