### ISSUE TITLE
Trying to write Grammer and Tree parser for SQL IN Operator

### ISSUE THREAD

**Issue by mahanteshck** [antlr/antlrcs#38]
I Am new to the Antlr, Started Going through "The Definitive ANTLR Reference". And in one of the existing product Antlr is already used for SQL statement parsing, and For some filter technique in the UI we need to parse IN Operator inside Where Clause. With the Implementation what I have done, I am able to get the Half result. (Code is in Antlr Version 3)
Combinations of IN Operator
-- IN (21) -- Works correct, even for (21, 86, 155)
-- IN (50-100) -- Works correct even for Multiple Ranges ( (50-100, 120-200, 350-420))
-- IN (21, 50-100)
-- IN (50-100, 21, 150-200)
-- IN (21, 50-100, 155)
-- IN (21, 86, 50-100, 155)
And all other scenario's it's not working as expected as I am missing some thing.
This is What I have written in the Grammar file:

```
.........
.......
// in expression
inExpression
	:	field_name RESERVED_NOT? RESERVED_IN^ inCondition	
	;

inCondition
	:	OPEN_PAREN! 
		( (select_statement) => select_statement
		| (inElement) (COMMA! inElement)*)
		CLOSE_PAREN!
	;

inElement
	: unary_expression
	| range_expression
	;

...........
............
unary_expression
	: constant
	;

// MCK
range_expression
	: unary_expression RANGE^ unary_expression
	;

constant 
	: INT 
	| FLOAT 
	| STRING 
	| CHAR
	;
```

In Tree Parser below is the Code which I have written, I am not able to figure out what needs to be done to support all the scanario's mentioned above for IN Operator.

```
joinCondition returns [SqlWhere cond = null;]
	@init {
		List<string> inList = new List<string>();
		bool notModifier = false;
		StringBuilder builder = new StringBuilder(255);
		List<string> rangeList = new List<string>();	
	}
: ^(RESERVED_IN field = fieldName (RESERVED_NOT { notModifier = true; })? ((node1 = unaryExpression 
		{		
			inList.Add(node1.Text);
		}
	)* 
	|
	(rlist = rangeExpression
		{
			foreach(CommonTree ritem in rlist)
			{
				rangeList.Add(ritem.Text);
			}
		}
	)* ) )
	{
		if(inList.Count > 0)
		{
			int i = 0;
		
			if (!field.IsComplex)
			{
				field.Parameters = parameters;
			
				// Append the field name into the buffer
				//builder.Append("(");
				builder.Append(field.ToString());
		
				// If the not modifier is being used
				if (notModifier)
				{
					builder.Append(" NOT ");
				}
		
				// Place the paren
				builder.Append(" IN (");
		
				// Build the in list
				foreach (string inItem in inList)
				{
					if (i == 0)
					{
						builder.Append(inItem);
					}
					else
					{
						builder.Append(", ");
						builder.Append(inItem);
					}
					i++;
				}
		
				builder.Append(')');
		
				if (field.Type == ColumnType.ForeignKey)
				{
					Query.AddSubQueryWhere(new SqlWhere(builder.ToString()));
				}
				else
				{
					$cond = new SqlWhere(builder.ToString());
				}
			}
		}				
		if (rangeList.Count > 0)
		{
			int i = 0;
			// build the rangeList with BETWEEN and AND
			foreach(string rangeItem in rangeList)
			{
				if (i == 0 || ((i \% 2) == 0))
				{
					if(inList.Count > 0 || i > 1)
					{
						builder.Append(" OR ");
					}
					builder.Append("(");
					builder.Append(field.ToString());
					builder.Append(" BETWEEN ");
					builder.Append(rangeItem);
					builder.Append(" AND ");
				}
				else
				{
					builder.Append(rangeItem);
					builder.Append(") ");
				}							
				i++;			
			}
			if (field.Type == ColumnType.ForeignKey)
			{
				Query.AddSubQueryWhere(new SqlWhere(builder.ToString()));
			}
			else
			{
				$cond = new SqlWhere(builder.ToString());
			}
		}		
	}
```
...
.....	
unaryExpression returns [string cons]
	: #(UNARY_MINUS conString = constant)
	{
		$cons = String.Format("-{0}", conString);
	}
	| #(UNARY_PLUS conString = constant)
	{
		$cons = conString;
	}
	| conString = constant
	{
		$cons = conString;
	}
	;

 // MCK
rangeExpression returns [List<string> row]
@init
	{
		$row = new List<string>();
	}
	: ^(RANGE left=unaryExpression right=unaryExpression)
	{
		$row.Add(left);
		$row.Add(right);
	}
	;

			
constant returns [string cons]
	: ni=INT 
	{
		$cons = ni.Text;
	}
	| nf=FLOAT 
	{
		$cons = nf.Text;
	}
	| sl=STRING 
	{
		$cons = "\"" + sl.Text + "\"";
	}
	| cl=CHAR
	{
		$cons = cl.Text;
	}
	;

Please Suggest.
Thanks A Lot in Advance.

Best Regards
Mahantesh C K

**Comment by mahanteshck** [comment]
Any Suggestions are much appreciated on the above problem.

**Comment by parrt** [comment]
that is a question not a bug.

**Comment by mahanteshck** [comment]
Yep. Can you please suggest me the way out. I have pasted the same Question on stackoverflow as well.
http://stackoverflow.com/questions/31300467/trying-to-write-grammer-and-tree-parser-for-sql-in-operator
