### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by sharwell** [antlr/antlrcs#42]
From @jeremymeng:

> According to https://oren.codes/2015/07/29/targeting-net-core/, class libraries using Profile 259 can run on CoreClr as-is.

:memo: This issue was split from #40.

**Comment by tlil87** [comment]
Hi @sharwell - do you have any roadmap for this, or even better, an ETA for when this will be done? Is it being worked on, or on hold for now?

**Comment by jeremymeng** [comment]
@sharwell Are you waiting for the RC2 release too?  Or is there anything we can help now to move this forward?  Thanks!

**Comment by lextm** [comment]
Seems like the discussion is now under antlr/antlr4#1142.

Though PCL profile 259 might run on .NET Core, I still think a dedicate port to .NET Core is required. The PCL port has removed too many APIs to adapt to the limited PCL API surface, while .NET Core (.NET Standard) does provide more. A dedicate port can add more types and ease the pains of migrating from .NET Framework to .NET Core.

**Comment by sharwell** [comment]
@lextm The other issue you linked to is for ANTLR 4. This is the repository for ANTLR 3.

A beta of ANTLR 4's [original C# target](https://github.com/tunnelvisionlabs/antlr4cs) with support for .NET Core was [released to NuGet](https://www.nuget.org/packages/Antlr4/4.5.3.1-beta001) a few weeks ago.

**Comment by jeremymeng** [comment]
In My PR I added a project.json.  Running `dotnet restore` then `dotnet pack` under `Runtime/Antlr3.Runtime/` should output a nupkg that targets the same set of frameworks as the old package does, and two more: `netstandar1.1` and `netstandard1.3`.

**Comment by sharwell** [comment]
This was fixed in #53 (for ANTLR 3) and #59 (for StringTemplate 4).

**Comment by jeremymeng** [comment]
@sharwell will there be a pre-release on nuget.org soon?

**Comment by richardsheppard-avalara** [comment]
@sharwell just wondering if this will be made available on nuget anytime soon?

**Comment by sharwell** [comment]
I don't have a specific timeline, but it's a blocker for some other things I want to get done so hopefully I can get it resolved in a reasonable time.
