### ISSUE TITLE
StringRenderer

### ISSUE THREAD

**Issue by tdjastrzebski** [antlr/antlrcs#46]
In StringRenderer line 67 is intended to handle formatting of all the formats, other than predefined.
However, it will never work since in line 48 attribute value is converted to string, and then String.Format() is used to format String type value.

Please modify line line 67 as follow:

```
return string.Format(culture, formatString, o);
```

Below my optimized implementation, handling html-encode.

Tomasz Jastrzębski

```csharp
public virtual string ToString(object o, string formatString, CultureInfo culture)
    {
        if (formatString == null) return o.ToString();

        switch (formatString) {
            case "upper":
                return o.ToString().ToUpper(culture);
            case "lower":
                return o.ToString().ToLower(culture);
            case "cap":
                string s = o.ToString();
                return s.Length > 0 ? Char.ToUpper(s[0], culture) + s.Substring(1) : s;
            case "url-encode":
                return HttpUtility.UrlEncode(o.ToString(), Encoding.UTF8);
            case "xml-encode":
                return SecurityElement.Escape(o.ToString());
            case "html-encode":
                return HttpUtility.HtmlEncode(o);
            default:
                return String.Format(culture, formatString, o);
        }
    }
```

**Comment by sharwell** [comment]
In its current form, `StringRenderer` is only intended to be registered for type `string`. As you can see from the cast on line 48 (which matches the cast used in the [original Java code](https://github.com/antlr/stringtemplate4/blob/1c5d129c6db9c4471291e7e670a628333eef892f/src/org/stringtemplate/v4/StringRenderer.java#L47)), it's clear that the input argument `o` is either `null` or an instance of `string`. In either case, the change you proposed to line 67 is equivalent to the current behavior.

To use this renderer with other types of objects, you can use StringTemplate's "to string" operator to render any other type to a string prior to using one of the string formats. This operator is applied by wrapping your expression in parentheses. For example, if `o` is any object, then `(o)` is a string which can be used with `StringRenderer`.

**Comment by tdjastrzebski** [comment]
Thank You for your response.

 

Looking at StringRenderer line 67 I assumed that the idea was to support format strings other than defined, while this will not work since the formatted value in line 67 is always of a string type.

return string.Format(culture, formatString, s);

vs.

return string.Format(culture, formatString, o);

 

However, if the aim is to maintain two way Java version compatibility I suggest replacing line 67 with simply:

return s;

since there is no point of formatting string value with String.Format().

Best to my knowledge, the Format() method will always return the supplied string value, no matter what formatString and culture is.

 

Best regards,

 

Tomasz

**Comment by sharwell** [comment]
Your format string could be `Text: {0}`. Wherever you put `{0}` in the format string, that's where the string argument will appear in the output. :smile:

**Comment by tdjastrzebski** [comment]
Btw, it looks like the original Java code has the same, I would say, defect in line 64 – since it is really not a bug, just an unnecessary call.

 

Is there any Antlr 4 online documentation available?

The links which worked in the past seen no longer valid.

 

Thanks,

 

Tomasz

**Comment by parrt** [comment]
Links to doc from antlr.org should be correct: https://github.com/antlr/antlr4/blob/master/doc/index.md

**Comment by tdjastrzebski** [comment]
Due to the issue I try to describe this will not likely work. Try:

 

string s = "$date;format=\"{0:R}\"$";

Template t1 = new Template(s, '$', '$');

t1.Add("date", DateTime.Now);

Console.WriteLine(t1.Render());

Console.ReadLine();

 

or

 

string s = "$date;format=\"{0:R}\"$";

TemplateGroup g1 = new TemplateGroup('$', '$');

g1.RegisterRenderer(typeof(object), new StringRenderer());

Template t1 = new Template(g1, s);

t1.Add("date", DateTime.Now);

Console.WriteLine(t1.Render());

Console.ReadLine();

**Comment by sharwell** [comment]
@tdjastrzebski `DateTime` is not `string`, so it cannot be formatted using `StringRenderer`. You would need to provide a new renderer if you want to control the way it gets formatted. One optional is creating a `FormattableRenderer` which you register for the `IFormattable` type, and when rendering objects you just do this:

```csharp
public virtual string ToString(object o, string formatString, CultureInfo culture)
{
  return ((IFormattable)o).ToString(formatString, culture);
}
```

**Comment by tdjastrzebski** [comment]
Ok, I must have misunderstood. In my current project I use own renderer – just one for all the types.

But, for future reference, I still try to understand the original design. Could you provide an example where formatting in StringRenderer line 67 will be applied?

**Comment by sharwell** [comment]
@tdjastrzebski Sure, change your original example to this:

```
$(date);format="The date was: {0}"$
```

**Comment by tdjastrzebski** [comment]
ic…

Is not that equivalent to shorter and cleaner:

„The date was: $(date)$”

?

**Comment by sharwell** [comment]
Not only is it shorter and cleaner, but Java and C# actually behave differently for this format string (bad if you want to use the same template in multiple target languages). While I probably wouldn't recommend it's use, it does demonstrate the behavior of the line you mentioned. :smile:

**Comment by tdjastrzebski** [comment]
So, there is no separate documentation just for String Template 4?

**Comment by tdjastrzebski** [comment]
I mean, seriously. Until recently, I always recommended StringTemplate in my, rather large, organization whenever things like email content had to be built etc. until I realized the only link to compact documentation I knew https://theantlrguy.atlassian.net/wiki/display/ST4/StringTemplate+cheat+sheet

is no longer publicly accessible. And I cannot recommend a product for which documentation is unavailable. Quite a pity :(

BR/TJ

 

From: Tomasz Jastrzębski [mailto:tdjastrzebski@wp.pl] 
Sent: Thursday, January 14, 2016 7:26 PM
To: 'antlr/antlrcs' <reply@reply.github.com>
Subject: RE: [antlrcs] StringRenderer (#46)

 

So, there is no separate documentation just for String Template 4?

**Comment by parrt** [comment]
It would be a pity that you couldn’t visit the websiteTo discover that the documentation is now part of the repository and that the documentation link clearly points to the new location. I even went to the trouble to make a Google remove it from search.
Ter

**Comment by tdjastrzebski** [comment]
Stupid me, so for my future reference, the link to StringTemplate documentation is

https://github.com/antlr/stringtemplate4/blob/master/doc/index.md

rather than

 <https://github.com/antlr/antlr4/blob/master/doc/index.md> https://github.com/antlr/antlr4/blob/master/doc/index.md

How could I have missed it?

Thanks,

TJ

**Comment by sharwell** [comment]
I don't see any action required at this time. The existing test `TestNumberRendererWithPrintfFormat` covers the scenario described above, so everything appears to be working as intended.
