### ISSUE TITLE
What nuget package

### ISSUE THREAD

**Issue by niemyjski** [antlr/antlrcs#47]
I noticed you guys created like 20 nuget package that all look the same. Which one should I use that is the latest version? Is this library still being maintained?

**Comment by ngbrown** [comment]
It seems that this repository is intending to publish to [Antlr3.Runtime](https://www.nuget.org/packages/Antlr3.Runtime), but the most recent version is the pre-release alpha002 and doesn't include any of the PLC options.

The AppVeyor configuration isn't incrementing a build number, so there's no differintiation between builds.  The next step would be publish what the AppVoyer NuGet feed is for the pre-release builds.

**Comment by ngbrown** [comment]
If #51 is merged and the CI build's NuGet feed is published, that will help provide access to the development builds.  Updating the official NuGet repository with released builds would be nice too.

**Comment by sharwell** [comment]
This repository contains C# versions of 3 major projects, some of which have multiple build artifacts:

* ANTLR 3
  * [Antlr3](https://www.nuget.org/packages/Antlr3): Code generator for ANTLR 3
  * [Antlr3.Runtime](https://www.nuget.org/packages/Antlr3.Runtime): Runtime library for ANTLR 3
  * [Antlr3.Runtime.Debug](https://www.nuget.org/packages/Antlr3.Runtime.Debug): Runtime library debugging tools for ANTLR 3
* StringTemplate 3
  * [StringTemplate3](https://www.nuget.org/packages/StringTemplate3): Runtime library
* StringTemplate 4
  * [StringTemplate4](https://www.nuget.org/packages/StringTemplate4): Runtime library
  * [StringTemplate4.Visualizer](https://www.nuget.org/packages/StringTemplate4.Visualizer): WPF visualizer for rendering StringTemplate 4 templates

**Comment by sharwell** [comment]
We're in the process of adding .NET Standard support to ANTLR 4. I'd like to figure out how to handle the code generation portion before trying to incorporate a similar strategy here. See tunnelvisionlabs/antlr4cs#110 for more information.
