### ISSUE TITLE
dotnet build fails to build a project containing Antrl3 targets

### ISSUE THREAD

**Issue by hazzik** [antlr/antlrcs#71]
Way to reproduce: 

The simplest possible project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="**/*.g" />
  </ItemGroup>
  <ItemGroup>
    <Antlr3 Include="**/*.g" />
  </ItemGroup>

  <ItemGroup>
      <PackageReference Include="Antlr3" Version="3.5.1" />
  </ItemGroup>

</Project>
```
Some grammar files (one empty `.g` file should do the trick)

```
C:\Projects\ttt>dotnet build
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\hazzik\.nuget\packages\antlr3\3.5.1\build\Antlr3.targets(126,5): error MSB4062: The "Antlr3.Build.Tasks.AntlrClassGenerationTask" task could not be loaded from the assembly C:\Users\hazzik\.nuget\pack
ages\antlr3\3.5.1\build\.\AntlrBuildTask.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the fil
e specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.I
Task. [C:\Projects\ttt\ttt.csproj]

Build FAILED.

C:\Users\hazzik\.nuget\packages\antlr3\3.5.1\build\Antlr3.targets(126,5): error MSB4062: The "Antlr3.Build.Tasks.AntlrClassGenerationTask" task could not be loaded from the assembly C:\Users\hazzik\.nuget\pack
ages\antlr3\3.5.1\build\.\AntlrBuildTask.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the fil
e specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.I
Task. [C:\Projects\ttt\ttt.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.82                                                                                                                                                                                     ```

**Comment by lextm** [comment]
A .NET Standard project (yours) should not depend on a .NET Framework project (ANTLR3). I think it is not a supported scenario.

**Comment by fredericDelaporte** [comment]
This happens with .Net Framework projects using VS 2017 .csproj format and `dotnet build` too.

**Comment by fredericDelaporte** [comment]
And it looks like Antlr3 supports .Net standard, or is the [Nuget page](https://www.nuget.org/packages/Antlr3.Runtime) wrong?

**Comment by hazzik** [comment]
@lextm I think you SHOULD delete your nonsense comment and don't waste anyone's valuable time anymore.

1. Antlr3 is a build tool package it shouldn't be anyhow related to the framework used by a project.
2. Antrl3.Runtime does indeed support .NET Standard 
3. I'll be waiting for your [PR](https://github.com/nhibernate/nhibernate-core/pull/new/master) with a "switch to ANTLR 4 latest beta build". How long do you think it will take you to do? I guess an hour. The timer has been set.

**Comment by hazzik** [comment]
@fredericDelaporte It's just a MsBuild task's fault: it has been built with the MsBuild 3.5. I think it should have include 3 separate tasks assemblies build with proper tooling for supported frameworks.

PS: Building from within VS works.

**Comment by fredericDelaporte** [comment]
Yes this issue is about the build, not about Antlr3.Runtime support of .Net Core, and I also expect the fix to be either an upgrade to the task assembly or having additional versions of this assembly using more up to date tooling. I was just giving some elements (true, maybe not the best, but sufficient I think) for discarding lextm comment which looks to me as suggesting a close.

**Comment by hazzik** [comment]
To solve the issue, the structure of the package shall be like following:

- build
  - net35 
    - Antlr3.props
    - Antlr3.targets
    - AntlrBuildTask.dll # Compiled against Microsoft.Build.Utilities.v3.5
  - net40 
    - Antlr3.props
    - Antlr3.targets
    - AntlrBuildTask.dll # Compiled against Microsoft.Build.Utilities.v4.0
  - net45 # Probably it is not required as net40 can handle this
    - Antlr3.props
    - Antlr3.targets
    - AntlrBuildTask.dll # Compiled against Microsoft.Build.Utilities.v12.0
  - net46
    - Antlr3.props
    - Antlr3.targets
    - AntlrBuildTask.dll # Compiled against [Microsoft.Build.Utilities.Core](https://www.nuget.org/packages/Microsoft.Build.Utilities.Core)
  - netstandard1.0
    - Antlr3.props
    - Antlr3.targets
    - AntlrBuildTask.dll # Compiled against [Microsoft.Build.Utilities.Core](https://www.nuget.org/packages/Microsoft.Build.Utilities.Core)

There is a possibility that net45 would be required if

**Comment by sharwell** [comment]
@hazzik That likely won't fix the problem. The subfolders of build represent the *target* framework, not the framework used to execute MSBuild itself.

**Comment by hazzik** [comment]
@sharwell it does actually fix the problem. (I've checked - it works). 

Here is the documentation: 

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package

> Files in the root \build folder are considered suitable for all target frameworks. To provide framework-specific files, first place those within appropriate subfolders, such as the following:
> ```
> \build
>     \netstandard1.4
>         \Contoso.Utility.UsefulStuff.props
>         \Contoso.Utility.UsefulStuff.targets
>     \net462
>         \Contoso.Utility.UsefulStuff.props
>         \Contoso.Utility.UsefulStuff.targets
> ```

**Comment by hazzik** [comment]
I've created a private alpha package (compiled by hands, changed name to Antlr3.Core) to test if it does work. These are .nuget.g.targets & .nuget.g.props  generated for a multi-target .netcore project (netstandard 1.5 & net 4.6.1):

.targets:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'net461' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)antlr3.core\3.5.1-alpha6\build\net45\Antlr3.Core.targets" Condition="Exists('$(NuGetPackageRoot)antlr3.core\3.5.1-alpha6\build\net45\Antlr3.Core.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'netstandard1.5' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)antlr3.core\3.5.1-alpha6\build\netstandard1.5\Antlr3.Core.targets" Condition="Exists('$(NuGetPackageRoot)antlr3.core\3.5.1-alpha6\build\netstandard1.5\Antlr3.Core.targets')" />
  </ImportGroup>
</Project>
```
.props:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">C:\Projects\ttt\obj\project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\hazzik\.nuget\packages\</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">4.3.0</NuGetToolVersion>
  </PropertyGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'net461' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)antlr3.core\3.5.1-alpha6\build\net45\Antlr3.Core.props" Condition="Exists('$(NuGetPackageRoot)antlr3.core\3.5.1-alpha6\build\net45\Antlr3.Core.props')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'netstandard1.5' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)antlr3.core\3.5.1-alpha6\build\netstandard1.5\Antlr3.Core.props" Condition="Exists('$(NuGetPackageRoot)antlr3.core\3.5.1-alpha6\build\netstandard1.5\Antlr3.Core.props')" />
  </ImportGroup>
</Project>
```

**Comment by hazzik** [comment]
I understood what you mean, yes, it does not run a specific MSBuild. But it works.

**Comment by sharwell** [comment]
After several days of work, I think I'm getting close to addressing this. 😅

**Comment by hazzik** [comment]
Thanks!

**Comment by sharwell** [comment]
@hazzik Note that this will required the 2.0 SDK to run `dotnet build`, but the application being compiled can target anything from .NET Standard 1.1 and newer.

**Comment by hazzik** [comment]
Thats fine for us:) Thanks. When the nuget package is due?

**Comment by sharwell** [comment]
I should have a beta up tonight. You'll be able to avoid beta dependencies at runtime by installing Antlr3.Runtime 3.5.1 and Antlr3.CodeGenerator 3.5.2-beta1 *instead* of installing the Antlr3 package that always adds both with the same version.

**Comment by sharwell** [comment]
@hazzik The code generator is published now.

**Comment by hazzik** [comment]
Thanks a lot!

**Comment by hazzik** [comment]
Works perfectly*. Thanks again.

* I did not check that it works on environments other than Windows.
