### ISSUE TITLE
I have some errors during compilation...

### ISSUE THREAD

**Issue by ArsenShnurkov** [antlr/antlrcs#84]
I am not using your build process, so it's not your error,
but i have question what is wrong with mine compilation

<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3.StringTemplate/Language/ActionEvaluatorHelper.cs#L71">Antlr3.StringTemplate/Language/ActionEvaluatorHelper.cs(71,30)</a>: error CS0115: 'ActionEvaluator.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3.StringTemplate/Language/ActionParserHelper.cs#L52">Antlr3.StringTemplate/Language/ActionParserHelper.cs(52,22)</a>: error CS0759: No defining declaration found for implementing declaration of partial method 'ActionParser.CreateTreeAdaptor(ref StringTemplateTreeAdaptor)'
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3.StringTemplate/Language/ActionParserHelper.cs#L57">Antlr3.StringTemplate/Language/ActionParserHelper.cs(57,30)</a>: error CS0115: 'ActionParser.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3.StringTemplate/Language/AngleBracketTemplateLexerHelper.cs#L50">Antlr3.StringTemplate/Language/AngleBracketTemplateLexerHelper.cs(50,30)</a>: error CS0115: 'AngleBracketTemplateLexer.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3.StringTemplate/Language/AngleBracketTemplateLexerHelper.cs#L55">Antlr3.StringTemplate/Language/AngleBracketTemplateLexerHelper.cs(55,34)</a>: error CS0115: 'AngleBracketTemplateLexer.TokenNames': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3.StringTemplate/Language/GroupParserHelper.cs#L43">Antlr3.StringTemplate/Language/GroupParserHelper.cs(43,30)</a>: error CS0115: 'GroupParser.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3.StringTemplate/Language/InterfaceParserHelper.cs#L43">Antlr3.StringTemplate/Language/InterfaceParserHelper.cs(43,30)</a>: error CS0115: 'InterfaceParser.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3.StringTemplate/Language/TemplateLexerHelper.cs#L44">Antlr3.StringTemplate/Language/TemplateLexerHelper.cs(44,34)</a>: error CS0115: 'TemplateLexer.TokenNames': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3.StringTemplate/Language/TemplateLexerHelper.cs#L58">Antlr3.StringTemplate/Language/TemplateLexerHelper.cs(58,30)</a>: error CS0115: 'TemplateLexer.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3.StringTemplate/Language/TemplateParserHelper.cs#L41">Antlr3.StringTemplate/Language/TemplateParserHelper.cs(41,30)</a>: error CS0115: 'TemplateParser.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr4.StringTemplate/Compiler/Group.g3.lexer.cs#L43">Antlr4.StringTemplate/Compiler/Group.g3.lexer.cs(43,30)</a>: error CS0115: 'GroupLexer.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr4.StringTemplate/Compiler/Group.g3.lexer.cs#L62">Antlr4.StringTemplate/Compiler/Group.g3.lexer.cs(62,32)</a>: error CS0115: 'GroupLexer.SourceName': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr4.StringTemplate/Compiler/Group.g3.parser.cs#L56">Antlr4.StringTemplate/Compiler/Group.g3.parser.cs(56,30)</a>: error CS0115: 'GroupParser.DisplayRecognitionError(string[], RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr4.StringTemplate/Compiler/Group.g3.parser.cs#L62">Antlr4.StringTemplate/Compiler/Group.g3.parser.cs(62,32)</a>: error CS0115: 'GroupParser.SourceName': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr4.StringTemplate/Compiler/TemplateParser.g3.cs#L50">Antlr4.StringTemplate/Compiler/TemplateParser.g3.cs(50,35)</a>: error CS0115: 'TemplateParser.RecoverFromMismatchedToken(IIntStream, int, BitSet)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr4.StringTemplate/Debug/DebugTemplate.cs#L79">Antlr4.StringTemplate/Debug/DebugTemplate.cs(79,34)</a>: error CS0115: 'DebugTemplate.CreateShadow(Template)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Grammars/ANTLRLexerHelper.cs#L48">Grammars/ANTLRLexerHelper.cs(48,34)</a>: error CS0115: 'ANTLRLexer.TokenNames': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Grammars/ANTLRLexerHelper.cs#L56">Grammars/ANTLRLexerHelper.cs(56,32)</a>: error CS0115: 'ANTLRLexer.NextToken()': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Grammars/ANTLRParserHelper.cs#L209">Grammars/ANTLRParserHelper.cs(209,22)</a>: error CS0759: No defining declaration found for implementing declaration of partial method 'ANTLRParser.CreateTreeAdaptor(ref ITreeAdaptor)'
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Grammars/ANTLRParserHelper.cs#L333">Grammars/ANTLRParserHelper.cs(333,30)</a>: error CS0115: 'ANTLRParser.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Grammars/ANTLRTreePrinterHelper.cs#L72">Grammars/ANTLRTreePrinterHelper.cs(72,30)</a>: error CS0115: 'ANTLRTreePrinter.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Grammars/AssignTokenTypesWalkerHelper.cs#L50">Grammars/AssignTokenTypesWalkerHelper.cs(50,30)</a>: error CS0115: 'AssignTokenTypesWalker.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Grammars/CodeGenTreeWalkerHelper.cs#L72">Grammars/CodeGenTreeWalkerHelper.cs(72,30)</a>: error CS0115: 'CodeGenTreeWalker.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Grammars/LeftRecursiveRuleWalker.g3.cs#L45">Grammars/LeftRecursiveRuleWalker.g3.cs(45,30)</a>: error CS0115: 'LeftRecursiveRuleWalker.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Grammars/TreeToNFAConverterHelper.cs#L151">Grammars/TreeToNFAConverterHelper.cs(151,30)</a>: error CS0115: 'TreeToNFAConverter.ReportError(RecognitionException)': no suitable method found to override
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Tool/AssignTokenTypesBehavior.cs#L45">Tool/AssignTokenTypesBehavior.cs(45,18)</a>: error CS0060: Inconsistent accessibility: base class 'AssignTokenTypesWalker' is less accessible than class 'AssignTokenTypesBehavior'
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Tool/Grammar.cs#L3607">Tool/Grammar.cs(3607,29)</a>: error CS0051: Inconsistent accessibility: parameter type 'TreeToNFAConverter' is less accessible than method 'Grammar.IsValidSet(TreeToNFAConverter, GrammarAST)'
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Tool/Grammar.cs#L3635">Tool/Grammar.cs(3635,32)</a>: error CS0051: Inconsistent accessibility: parameter type 'TreeToNFAConverter' is less accessible than method 'Grammar.GetSetFromRule(TreeToNFAConverter, string)'
<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Tool/LeftRecursiveRuleAnalyzer.cs#L49">Tool/LeftRecursiveRuleAnalyzer.cs(49,18)</a>: error CS0060: Inconsistent accessibility: base class '<a href="https://github.com/antlr/antlrcs/blob/ca331b7109e1faa5a6aa7336bb6281ce9363e62b/Antlr3/Grammars/LeftRecursiveRuleWalker.g3.cs#L38">LeftRecursiveRuleWalker</a>' is less accessible than class 'LeftRecursiveRuleAnalyzer'

**Comment by sharwell** [comment]
This repository requires Visual Studio 2017 Update 3 or newer to build (Community Edition will work). With that installed, you should be able to open Antlr3.sln and build successfully.

**Comment by ArsenShnurkov** [comment]
I am on Sabayon Linux and don't want to/not able to install Visual Studio 2017. That's why I create separate build scripts (package this tool).

**Comment by sharwell** [comment]
For those cases, the only supported option would be referencing the release binaries through NuGet. You can find a list of packages in the main readme:
https://github.com/antlr/antlrcs
