### ISSUE TITLE
Does Antlr have an ECCN?

### ISSUE THREAD

**Issue by otramony** [antlr/antlrcs#85]
Hello. Our team would like to use/include your library in our product, and since we export outside of the U.S., we're required to provide ECCN (Export Control Classification Number) information for all 3rd-party libraries that may use/include encryption.

**Comment by sharwell** [comment]
**I am not a lawyer.**

ANTLR does not itself implement encryption, and based on a cursory look at EAR 742 it does not appear that ANTLR would be subject to classification. However, ANTLR has dependencies (varies by runtime), and some of those dependencies may be classified separately.

I expect the best information you are likely to get here is "unspecified", meaning the consumer of the library is responsible for determining the requirements for redistribution according to the laws of the country and the [ANTLR license](https://github.com/antlr/antlrcs/blob/master/LICENSE.txt).

**Comment by otramony** [comment]
This will suffice. Thank you.
